---
- name: Install ZFS
  tags: zfs
  become: true
  block:
    - name: Install ZFS
      apt:
        name: zfsutils-linux
        update_cache: yes

    - name: Configure datasets
      zfs:
        name: "{{ item.key }}"
        extra_zfs_properties: "{{ item.value or omit }}"
        state: present
      with_dict: "{{ zfs_datasets }}"
- name: Load ZFS encryption keys automatically on boot
  tags:
    - zfs
    - encryption
  become: true
  when: zfs_boot_load_keys
  block:
    - name: Create systemd drop-in directory
      file:
        path: /etc/systemd/system/zfs-mount.service.d
        state: directory
        mode: '0755'
    - name: Ensure encrption keys are loaded on boot
      copy:
        content: |
          [Unit]
          Description=Load ZFS encryption keys
          [Service]
          ExecStartPre=/usr/sbin/zfs load-key -a
        dest: /etc/systemd/system/zfs-mount.service.d/load-key.conf
        mode: '0644'
