---
- name: Install ZFS
  tags: zfs
  become: true
  block:
    - name: Install contrib repo
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib
        state: present
        filename: '{{ ansible_distribution_release }}-contrib'
        update_cache: true

    - name: Install ZFS
      apt:
        name: zfsutils-linux

    - name: Configure datasets
      zfs:
        name: "{{ item.key }}"
        extra_zfs_properties: "{{ item.value or omit }}"
        state: present
      with_dict: "{{ zfs_datasets }}"
